ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name = "cart"
urlpatterns = [
    path('addtocart/<int:p>', views.addtocart, name = "addtocart"),
    path('cart_remove/<int:p>', views.cart_remove, name = "cart_remove"),
    path('full_remove/<int:p>', views.full_remove, name = "full_remove"),
    path('cartview', views.cart_view, name = "cartview"),
    path('orderform', views.orderform, name = "orderform"),
    path('orderview', views.order_view, name = "orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name = "search"
urlpatterns = [
   path('search/', views.search_products, name = 'search_products'),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name = "shop"

urlpatterns = [
    path('', views.allcategories, name = "allcat"),
    path('products/<int:p>', views.allproducts, name = "products"),
    path ('detail/<int:p>', views.showdetail, name = "detail"),
    path ('reg', views.register, name = "register"),
    path ('log', views.user_login, name = "login"),
    path ('logout', views.user_logout, name = "logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add = True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    no_of_items = models.IntegerField()
    ordered_date = models.DateTimeField(auto_now_add=True)
    address = models.TextField()
    phone = models.BigIntegerField()
    order_status = models.CharField(max_length=30, default="pending")
    delivery_status = models.CharField(max_length=30, default="pending")

    def __str_(self):
        return self.user.username

class Account(models.Model):
    acctnum = models.BigIntegerField()
    accttype = models.CharField(max_length=20)
    amount = models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart, Order, Account
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

@login_required
def cart_view(request):
    u = request.user
    total = 0
    c = Cart.objects.filter(user=u)
    for i in c:
        total = total+i.quantity*i.product.price

    return render(request, 'cart.html',{'c': c, 'total':total})

@login_required
def addtocart(request, p):
    p = Product.objects.get(id=p)  # getting the particular product
    u = request.user  # to get the details and records of the current user login

    try:
        cart = Cart.objects.get(user=u,product=p)  # this is to check if the cart has that particular product already for the user.
        if (p.stock > 0):  # only increment till stock is available
            cart.quantity += 1  # if the cart already has the product for the user, then increment quantity by '1'.
            cart.save()  # save the cart details.
            p.stock -= 1  # to decrement the stock value when products are added to the cart
            p.save()  # save p

    except:  # if cart doesnt have that product for the user then create a new record for the cart.
        if (p.stock > 0):
            cart = Cart.objects.create(product=p, user=u,quantity=1)  # creates a new record in the cart table with product,user,and quantity as '1' initially.
            cart.save()
            p.stock-= 1
            p.save()

    return cart_view(request)

def cart_remove(request,p):
    p = Product.objects.get(id=p)  # getting the particular product
    u = request.user  # to get the details and records of the current user login

    try:
        cart = Cart.objects.get(user=u,product=p)  # this is to check if the cart has that particular product already for the user.
        if (cart.quantity > 1):
            cart.quantity -= 1  # it decrements the quantity
            cart.save()  # save the cart details.
            p.stock += 1  # it increments the available the stock.
            p.save()  # save p
        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
        pass

    return cart_view(request)

def full_remove(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass

    return cart_view(request)

@login_required()
def orderform(request):
    if (request.method == "POST"):
        print('hello')
        a = request.POST['a']
        p = request.POST['p']
        n = request.POST['n']
        u = request.user
        c = Cart.objects.filter(user=u)
        total = 0
        for i in c:
            total = total + i.quantity * i.product.price
        try:
            ac = Account.objects.get(acctnum=n)
            if (ac.amount >= total):
                ac.amount = ac.amount-total
                ac.save()
                for i in c:
                    o = Order.objects.create(user=u, product=i.product, address=a, phone=p, no_of_items=i.quantity, order_status="paid")
                    o.save()

                c.delete()
                msg = "Order Placed Successfully"
                return render(request, 'orderdetail.html', {'message': msg})
            else:
                msg = "Insufficient Amount. You can't Place Order"
                return render(request, 'orderdetail.html', {'message': msg})
        except:
            pass
    return render(request, 'orderform.html')

def order_view(request):
    u = request.user
    o = Order.objects.filter(user=u)
    return render(request, 'orderview.html', {'o':o, 'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def search_products(request):
    p = None
    query = ""
    if(request.method == "POST"):
        query = request.POST['q']
        if query:
            p = Product.objects.filter(Q(name__icontains = query) | Q(desc__icontains = query))
    return render(request, 'search.html', {'p':p, 'q':query})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel = "stylesheet" href = "{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body style = " background-color : #CECECE ">

<div class = "container-fluid">
<center>
    <img src = "{% static 'images/logo.jpg'%}" height = "120px" width = "120px"></center></div>

<div class="container-fluid">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> <b>E-Shop</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            AllCategories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        {% if user.is_superuser != True %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style = "font-size:25px;" href="{% url 'cart:cartview' %}"><i class = "fa-solid fa-cart-shopping"> <sup> {{count}} </sup> </i> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" style = "font-size:25px;" href="{% url 'cart:orderview' %}"> Your Orders </a>
        </li>
        {% endif %}

        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
      <form class="d-flex" method = "POST" action = "{% url 'search:search_products' %}">
          {% csrf_token %}
        <input class="form-control me-2" name = "q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

</div>
{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm">
                <span style="border-left: 2px solid #ccc; height: 20px; margin-right: 10px;"></span>
                <div class="my-4">
                    <a href="#">Terms of Service</a> |
                    <a href="#">DMCA</a> |
                    <a href="#">Contact</a> |
                    <a href="#">E-Shop</a>
                    <a href="#"><b>SOOHAN</b></a>
                </div>
                <p class="foot_text">&copy; Eshop. All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid mt-5" style="margin-bottom:100px">
    <div class="row">
        <h4 class="text-center text-light">Shopping Cart</h4>
        <div class="col-7 border border-1">
            <table class = "table table-bordered">
                <tr>
                    <th class = "text-center" colspan = "6"> Cart Items </th>
                </tr>
                {% for i in c %}
                 <tr>
                     <td> <img src = "{{i.product.image.url}}" height = "150px" width = "150px"></td>
                     <td><b>{{i.product.name}}</b></td>
                     <td><b>Product ID: {{i.product.id}}</b><br>
                     <b>Quantity:{{i.quantity}}</b><br>
                     <b>Unit Price:{{i.quantity}}*{{i.product.price}}</b><br></td>
                     <td> Subtotal:{{i.subtotal}}</td>
                     <td>
                         {% if i.product.stock > 0 %}
                         <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus" style="color:white;font-size:25px;"></i>
                     <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus" style="color:white;font-size:25px;"></i></a>
                           <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash" style="color:white;font-size:25px;"></i></a>

                             {% else %}
                             <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus" style="color:white;font-size:25px;"></i></a>
                           <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash" style="color:white;font-size:25px;"></i></a>
                               {% endif %}
                         </a>
                     </td>
                 </tr>

                 {% endfor %}
            </table>
        </div>

        <div class="col-4 border border-1">
            <table class = "table table-bordered">
                <tr>
                    <th colspan = "4" class = "text-center fw-bolder"> Check Out </th>
                </tr>
                <tr>
                    <td colspan = "4"> TOTAL AMOUNT : {{total}} </td>
                </tr>
            </table>
            <a class = "btn btn-secondary" href = "{% url 'cart:orderform' %}"> Place Order </a>
             <a class = "btn btn-secondary" href = "{% url 'shop:allcat' %}"> Continue Shopping </a>
        </div>
    </div>

{% endblock %}

</div>

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class = "container-fluid mt-1" style = "margin-bottom:100px">
    <img src = "{% static 'images/download.jpg' %}" height = "450px" width = "100%">
</div>

<div class = "container-fluid mt-1" style = "margin-bottom:100px">
    <h3 class = "text-center fw-bold"> Our Collections </h3>
    <p style = "text-align:justify; line-height:2"> Online Market-Place </p>
</div>

<div class = "container-fluid mt-1" style = "margin-bottom:200px">
        <div class = "row">
            {% for i in c %}
                <div class = "col-sm-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{i.image.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{i.name}}</h5>
                                <a href="{% url 'shop:products' i.id %}" class="btn btn-primary">Products</a>
                            </div>
                        </div>
                </div>
              {% endfor %}
            </div>
</div>

{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class = "container" style = "margin-bottom:100px;">
    <div class = "row mt-5">
        <div class = "col-4 me-5 pt-4" style = "padding-left:100px;">
            <img class = "mt-2" src = "{{p.image.url}}" height = "320px" width = "300px">
        </div>
        <div class = "col-6 me-5 mt-2 p-3" style = "padding-left:100px; width:750px;">
            <h3 class = "text-light"> {{p.name}} </h3>
            <p style = "text-align:justify;line-height:2;"> {{p.desc}} </p>
            <h5 class = "mt-2"> {{p.price}} </h5>
            <h6 class = "mt-2"> {{p.stock}} </h6>
            {% if user.is_superuser == True %}

            {% if p.stock > 0 %}
            <h3 class = "text-success"> Product in Stock </h3>
            <a href="{% url 'admin:index' %}" class = "btn btn-secondary mt-4" style = "width:300px;"> Add Stock </a>
            {% else %}
            <h3 class = "text-danger"> Product Out of Stock </h3>
            <a href="{% url 'admin:index' %}" class = "btn btn-secondary mt-4" style = "width:300px;"> Add Stock </a>
            {% endif %}


            {% else %}
            {% if p.stock > 0 %}
            <a href="{% url 'cart:addtocart' p.id %}" class = "btn btn-secondary mt-4" style = "width:300px;"> Add to Cart </a>
            {% else %}
            <h3 class = "text-danger"> Out of Stock </h3>
            {% endif %}

            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}
{% block content %}
<div class = "container" style = "margin-bottom:100px">
<h1 class = "text-center"> This is login page </h1>

    <form method="POST">
      {% csrf_token %}
        <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name = "u" placeholder="Enter Username">
    </div>

    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control"  name = "p" placeholder="Enter Password">
    </div>

        <div class = "mb-3">
    <input type="submit" class = "form-control">
        </div>
 </div>
</form>

{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% block content %}
<div class = "container mt-5">
    <h3 class = "text-center text-success"> {{message}} </h3>
    <h6 class = "text-center text-warning"> Thank You </h6>
    <h5 class = "text-center text-light"> <a href = "{% url 'shop:allcat' %}" class = "btn btn-danger"> Continue Shopping </a></h5>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px" xmlns="http://www.w3.org/1999/html">
<h1 class = "text-center"> Enter the Details...... </h1>

    <form method="POST">
      {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control" name = "a" placeholder="Enter Address">
    </div>

    <div class="mb-3">
      <label class="form-label">Phone Number</label>
      <input type="number" class="form-control"  name = "p" placeholder="Enter Phone Number">
    </div>

    <div class="mb-3">
      <label class="form-label">Account Number</label>
      <input type="number" class="form-control"  name = "n" placeholder="Enter Account Number">
    </div>


    <input type="submit">

</form></center>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="container mt-5">
<h5 class="text-center">Name of the Customer:{{u}}</h5>
    {% for i in o %}
    <div class="row">


        <div class="col-4 mt-3"><img src="{{i.product.image.url}}" height="150px" width="150px"></div>
        <div class="col-4 mt-3">
            <b>Product Name:{{i.product.name}}</b> <br>
            <b>Product Price:{{i.product.price}}</b> <br>
            <b>Delivery Address:{{i.address}}</b> <br>
            <b>Phone Number:{{i.phone}}</b> <br>
            <b>No. of items:{{i.product.quantity}}</b> <br>
            <b>Order Date:{{i.ordered_date}}</b> <br>
            <b>Delivery Status:{{i.delivery_status}}</b> <br>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class = "container-fluid mt-1" style = "margin-bottom:100px">
    <img src = "{{c.image.url}}" height = "450px" width = "100%">
</div>

<div class = "container-fluid mt-1" style = "margin-bottom:100px">
    <h3 class = "text-center fw-bold"> {{c.name}} </h3>
    <p style = "text-align:justify; line-height:2"> {{c.desc}}> </p>
</div>

<div class = "container-fluid mt-1" style = "margin-bottom:100px">
        <div class = "row">
            {% for i in p %}
                <div class = "col-sm-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{i.image.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{i.name}}</h5>
                                <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">Products</a>
                            </div>
                        </div>
                </div>
              {% endfor %}
            </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}
{% block content %}

<div class="container" style="margin-bottom:200px" xmlns="http://www.w3.org/1999/html">
<h1 class = "text-center"> Register </h1>

    <form method="POST">
      {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name = "u" placeholder="Enter Username">
    </div>

    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control"  name = "p" placeholder="Enter Password">
    </div>

    <div class="mb-3">
      <label class="form-label">Confirm Password</label>
      <input type="password" class="form-control"  name = "cp" placeholder="Confirm Password">
    </div>

     <div class="mb-3">
      <label class="form-label">Email Id</label>
      <input type="text" class="form-control"  name = "e" placeholder="Enter Your Mail Id">
    </div>

    <div class="mb-3">
      <label class="form-label">First Name</label>
      <input type="text" class="form-control"  name = "f" placeholder="Enter FirstName">
    </div>

    <div class="mb-3">
      <label class="form-label">Last Name</label>
      <input type="text" class="form-control"  name = "l" placeholder="Enter LastName">
    </div>


    <input type="submit">

</form> </center>
    </div>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% block content %}
<center>
    <div class = "container-fluid">
        <h3 class = "text-center"> You have searched for <span class = "text-danger"> {{q}} </span></h3>
    </div>
</center>
<div class = "container-fluid mt-1" style = "margin-bottom:100px">
        <div class = "row">
            {% for i in p %}
                <div class = "col-sm-4">
                    <div class="card rounded-3" style="width: 18rem;">
                        <img src="{{i.image.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{i.name}}</h5>
                                <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">Products</a>
                            </div>
                        </div>
                </div>


{% empty %}
<h5 class = "text-center text-danger"> No Results Found </h5>

{% endfor %} </div>
            </div>
{% endblock %}